ALTER TABLE "pricing_schedule_entries" ALTER COLUMN "provider" SET DATA TYPE text;
--> statement-breakpoint
-- 0062: pricing schedule v2 — supersedes the 0053 seed after MODEL_PRICING gained the google (Gemini)
-- and deepseek models (2026-08-15). Same immutable-seed design as 0053: the v1 schedule rows are HISTORY and
-- stay untouched; a NEW schedule is inserted and the GLOBAL pointer moves to it. The ALTER above moves the
-- entries' provider column to text so this seed (and any future one) can reference providers whose enum
-- values were added in the SAME migration batch — Postgres <18 rejects that for enum columns (55P04).
-- The platform_pricing_state immutability trigger (created by rls.sql, so absent during a fresh-DB
-- bootstrap) is disabled around the pointer UPDATE — migrations ARE the platform seeding path the trigger's
-- design carves out ("only the migration/platform (superuser) role seeds these rows").
-- Generated by scripts/dev/generate-pricing-seed-0062.ts.
INSERT INTO "pricing_schedules" ("id","source_pricing_version","currency","schedule_hash","canonicalization_version","hash_algorithm","seeded_by_migration") VALUES ('f00d0062-0000-4000-8000-000000000001','2026-07-24','USD','e2b61085d6de155746863990bf5cca6b6c0f638307263cf4c0675d7b42fdfded',1,'sha256','0062_pricing_schedule_v2');
--> statement-breakpoint
INSERT INTO "pricing_schedule_entries" ("schedule_id","provider","model","input_unit_price_micros","output_unit_price_micros","token_unit_size","unit_definition","min_charge_micros","max_output_tokens","valid_from","valid_until") VALUES
  ('f00d0062-0000-4000-8000-000000000001','anthropic','claude-haiku-4-5-20251001',1000000,5000000,1000000,'per_1m_tokens',NULL,64000,NULL,NULL),
  ('f00d0062-0000-4000-8000-000000000001','anthropic','claude-opus-4-8',5000000,25000000,1000000,'per_1m_tokens',NULL,64000,NULL,NULL),
  ('f00d0062-0000-4000-8000-000000000001','anthropic','claude-sonnet-5',2000000,10000000,1000000,'per_1m_tokens',NULL,64000,NULL,'2026-09-01T00:00:00.000Z'),
  ('f00d0062-0000-4000-8000-000000000001','deepseek','deepseek-chat',270000,1100000,1000000,'per_1m_tokens',NULL,8192,NULL,NULL),
  ('f00d0062-0000-4000-8000-000000000001','deepseek','deepseek-reasoner',550000,2190000,1000000,'per_1m_tokens',NULL,64000,NULL,NULL),
  ('f00d0062-0000-4000-8000-000000000001','google','gemini-3-flash',300000,2500000,1000000,'per_1m_tokens',NULL,65536,NULL,NULL),
  ('f00d0062-0000-4000-8000-000000000001','google','gemini-3-pro',2000000,12000000,1000000,'per_1m_tokens',NULL,65536,NULL,NULL),
  ('f00d0062-0000-4000-8000-000000000001','openai','gpt-5.4',2500000,15000000,1000000,'per_1m_tokens',NULL,65536,NULL,NULL),
  ('f00d0062-0000-4000-8000-000000000001','openai','gpt-5.4-mini',750000,4500000,1000000,'per_1m_tokens',NULL,65536,NULL,NULL);
--> statement-breakpoint
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'platform_pricing_state_immutable') THEN
    EXECUTE 'ALTER TABLE platform_pricing_state DISABLE TRIGGER platform_pricing_state_immutable';
  END IF;
  UPDATE platform_pricing_state
    SET current_pricing_schedule_id = 'f00d0062-0000-4000-8000-000000000001',
        current_pricing_schedule_hash = 'e2b61085d6de155746863990bf5cca6b6c0f638307263cf4c0675d7b42fdfded',
        seeded_by_migration = '0062_pricing_schedule_v2'
    WHERE singleton_key = 'GLOBAL';
  IF EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'platform_pricing_state_immutable') THEN
    EXECUTE 'ALTER TABLE platform_pricing_state ENABLE TRIGGER platform_pricing_state_immutable';
  END IF;
END
$$;
