-- 0070: pricing schedule v5 — CORRECTION of v4 (0069). The verified Claude Sonnet 5 STANDARD rate is
-- $2/$10 per M tokens; v4 (0069) seeded a $3/$15 rise that was never actually in effect. v4 merged to main;
-- whether it was ever applied to a live (staging/production) database is UNCONFIRMED as of this migration.
-- This is a forward correction that supersedes v4 regardless of where v4 was applied. Same immutable-seed
-- design: prior schedule rows are HISTORY and stay untouched; a NEW schedule is inserted and the GLOBAL pointer
-- moves. Data-only migration (no schema change) — it does not read or modify usage_events.

-- The platform_pricing_state immutability trigger (created by rls.sql, so absent during a fresh-DB
-- bootstrap) is disabled around the pointer UPDATE — migrations ARE the platform seeding path the trigger's
-- design carves out ("only the migration/platform (superuser) role seeds these rows").
-- Generated by scripts/dev/generate-pricing-seed-0070.ts.
INSERT INTO "pricing_schedules" ("id","source_pricing_version","currency","schedule_hash","canonicalization_version","hash_algorithm","seeded_by_migration") VALUES ('f00d0070-0000-4000-8000-000000000001','2026-07-24','USD','1f4392ae98206b304fddea7914e67284d3296a684061bd7e718c97af704842d6',1,'sha256','0070_pricing_schedule_v5');
--> statement-breakpoint
INSERT INTO "pricing_schedule_entries" ("schedule_id","provider","model","input_unit_price_micros","output_unit_price_micros","token_unit_size","unit_definition","min_charge_micros","max_output_tokens","valid_from","valid_until") VALUES
  ('f00d0070-0000-4000-8000-000000000001','anthropic','claude-haiku-4-5-20251001',1000000,5000000,1000000,'per_1m_tokens',NULL,64000,NULL,NULL),
  ('f00d0070-0000-4000-8000-000000000001','anthropic','claude-opus-4-8',5000000,25000000,1000000,'per_1m_tokens',NULL,64000,NULL,NULL),
  ('f00d0070-0000-4000-8000-000000000001','anthropic','claude-sonnet-5',2000000,10000000,1000000,'per_1m_tokens',NULL,64000,NULL,NULL),
  ('f00d0070-0000-4000-8000-000000000001','deepseek','deepseek-chat',270000,1100000,1000000,'per_1m_tokens',NULL,8192,NULL,NULL),
  ('f00d0070-0000-4000-8000-000000000001','deepseek','deepseek-reasoner',550000,2190000,1000000,'per_1m_tokens',NULL,64000,NULL,NULL),
  ('f00d0070-0000-4000-8000-000000000001','google','gemini-3.1-flash-lite',300000,2500000,1000000,'per_1m_tokens',NULL,65536,NULL,NULL),
  ('f00d0070-0000-4000-8000-000000000001','google','gemini-3.1-pro-preview',2500000,15000000,1000000,'per_1m_tokens',NULL,65536,NULL,NULL),
  ('f00d0070-0000-4000-8000-000000000001','openai','gpt-5.4',2500000,15000000,1000000,'per_1m_tokens',NULL,65536,NULL,NULL),
  ('f00d0070-0000-4000-8000-000000000001','openai','gpt-5.4-mini',750000,4500000,1000000,'per_1m_tokens',NULL,65536,NULL,NULL);
--> statement-breakpoint
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'platform_pricing_state_immutable') THEN
    EXECUTE 'ALTER TABLE platform_pricing_state DISABLE TRIGGER platform_pricing_state_immutable';
  END IF;
  UPDATE platform_pricing_state
    SET current_pricing_schedule_id = 'f00d0070-0000-4000-8000-000000000001',
        current_pricing_schedule_hash = '1f4392ae98206b304fddea7914e67284d3296a684061bd7e718c97af704842d6',
        seeded_by_migration = '0070_pricing_schedule_v5'
    WHERE singleton_key = 'GLOBAL';
  IF EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'platform_pricing_state_immutable') THEN
    EXECUTE 'ALTER TABLE platform_pricing_state ENABLE TRIGGER platform_pricing_state_immutable';
  END IF;
END
$$;
