/**
 * One-shot generator for drizzle/0063_pricing_schedule_v3.sql. Emits the seed
 * SQL from the SAME functions the tests verify against (buildSeedEntries /
 * computeSeedScheduleHash), so the migration literal cannot drift from the
 * runtime expectation. Kept in-repo for provenance; safe to re-run (it only
 * rewrites the migration file).
 */
import { writeFileSync } from 'node:fs';
import {
  PRICING_SOURCE_VERSION,
  SEED_MIGRATION_ID,
  SEED_SCHEDULE_ID,
  buildSeedEntries,
  computeSeedScheduleHash,
} from '../../src/domain/pricing/pricing-foundation';

const hash = computeSeedScheduleHash();
const entries = buildSeedEntries();
const lit = (v: string | bigint | null): string => (v === null ? 'NULL' : `'${v}'`);

const rows = entries
  .map(
    (e) =>
      `  ('${SEED_SCHEDULE_ID}','${e.provider}','${e.model}',${e.inputUnitPriceMicros},${e.outputUnitPriceMicros},${e.tokenUnitSize},'${e.unitDefinition}',${e.minChargeMicros === null ? 'NULL' : e.minChargeMicros},${e.maxOutputTokens},${lit(e.validFrom)},${lit(e.validUntil)})`,
  )
  .join(',\n');

// No schema DDL in this migration — the seed is the whole content.
const sql = `-- 0063: pricing schedule v3 — corrects the Gemini model ids (live-probed 2026-08-15): gemini-3-flash/-pro
-- 404 on the real API; v3 seeds gemini-3.1-flash-lite / gemini-3.1-pro-preview. Same immutable-seed design: prior
-- schedule rows are HISTORY and stay untouched; a NEW schedule is inserted and the GLOBAL pointer moves. The
-- provider column is already text (0062), so enum-commit timing cannot bite.

-- The platform_pricing_state immutability trigger (created by rls.sql, so absent during a fresh-DB
-- bootstrap) is disabled around the pointer UPDATE — migrations ARE the platform seeding path the trigger's
-- design carves out ("only the migration/platform (superuser) role seeds these rows").
-- Generated by scripts/dev/generate-pricing-seed-0063.ts.
INSERT INTO "pricing_schedules" ("id","source_pricing_version","currency","schedule_hash","canonicalization_version","hash_algorithm","seeded_by_migration") VALUES ('${SEED_SCHEDULE_ID}','${PRICING_SOURCE_VERSION}','USD','${hash}',1,'sha256','${SEED_MIGRATION_ID}');
--> statement-breakpoint
INSERT INTO "pricing_schedule_entries" ("schedule_id","provider","model","input_unit_price_micros","output_unit_price_micros","token_unit_size","unit_definition","min_charge_micros","max_output_tokens","valid_from","valid_until") VALUES
${rows};
--> statement-breakpoint
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'platform_pricing_state_immutable') THEN
    EXECUTE 'ALTER TABLE platform_pricing_state DISABLE TRIGGER platform_pricing_state_immutable';
  END IF;
  UPDATE platform_pricing_state
    SET current_pricing_schedule_id = '${SEED_SCHEDULE_ID}',
        current_pricing_schedule_hash = '${hash}',
        seeded_by_migration = '${SEED_MIGRATION_ID}'
    WHERE singleton_key = 'GLOBAL';
  IF EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'platform_pricing_state_immutable') THEN
    EXECUTE 'ALTER TABLE platform_pricing_state ENABLE TRIGGER platform_pricing_state_immutable';
  END IF;
END
$$;
`;

writeFileSync('drizzle/0063_pricing_schedule_v3.sql', sql);
console.log('wrote 0062 seed:', { hash, entries: entries.length });
