/**
 * One-shot generator for drizzle/0070_pricing_schedule_v5.sql. Emits the seed
 * SQL from the SAME functions the tests verify against (buildSeedEntries /
 * computeSeedScheduleHash), so the migration literal cannot drift from the
 * runtime expectation. Kept in-repo for provenance; safe to re-run (it only
 * rewrites the migration file — run it AFTER the empty custom migration has
 * been scaffolded by `drizzle-kit generate --custom --name pricing_schedule_v5`).
 */
import { writeFileSync } from 'node:fs';
import {
  PRICING_SOURCE_VERSION,
  SEED_MIGRATION_ID,
  SEED_SCHEDULE_ID,
  buildSeedEntries,
  computeSeedScheduleHash,
} from '../../src/domain/pricing/pricing-foundation';

const hash = computeSeedScheduleHash();
const entries = buildSeedEntries();
const lit = (v: string | bigint | null): string => (v === null ? 'NULL' : `'${v}'`);

const rows = entries
  .map(
    (e) =>
      `  ('${SEED_SCHEDULE_ID}','${e.provider}','${e.model}',${e.inputUnitPriceMicros},${e.outputUnitPriceMicros},${e.tokenUnitSize},'${e.unitDefinition}',${e.minChargeMicros === null ? 'NULL' : e.minChargeMicros},${e.maxOutputTokens},${lit(e.validFrom)},${lit(e.validUntil)})`,
  )
  .join(',\n');

// No schema DDL in this migration — the seed is the whole content.
const sql = `-- 0070: pricing schedule v5 — CORRECTION of v4 (0069). The verified Claude Sonnet 5 STANDARD rate is
-- $2/$10 per M tokens; v4 (0069) seeded a $3/$15 rise that was never actually in effect. v4 merged to main;
-- whether it was ever applied to a live (staging/production) database is UNCONFIRMED as of this migration.
-- This is a forward correction that supersedes v4 regardless of where v4 was applied. Same immutable-seed
-- design: prior schedule rows are HISTORY and stay untouched; a NEW schedule is inserted and the GLOBAL pointer
-- moves. Data-only migration (no schema change) — it does not read or modify usage_events.

-- The platform_pricing_state immutability trigger (created by rls.sql, so absent during a fresh-DB
-- bootstrap) is disabled around the pointer UPDATE — migrations ARE the platform seeding path the trigger's
-- design carves out ("only the migration/platform (superuser) role seeds these rows").
-- Generated by scripts/dev/generate-pricing-seed-0070.ts.
INSERT INTO "pricing_schedules" ("id","source_pricing_version","currency","schedule_hash","canonicalization_version","hash_algorithm","seeded_by_migration") VALUES ('${SEED_SCHEDULE_ID}','${PRICING_SOURCE_VERSION}','USD','${hash}',1,'sha256','${SEED_MIGRATION_ID}');
--> statement-breakpoint
INSERT INTO "pricing_schedule_entries" ("schedule_id","provider","model","input_unit_price_micros","output_unit_price_micros","token_unit_size","unit_definition","min_charge_micros","max_output_tokens","valid_from","valid_until") VALUES
${rows};
--> statement-breakpoint
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'platform_pricing_state_immutable') THEN
    EXECUTE 'ALTER TABLE platform_pricing_state DISABLE TRIGGER platform_pricing_state_immutable';
  END IF;
  UPDATE platform_pricing_state
    SET current_pricing_schedule_id = '${SEED_SCHEDULE_ID}',
        current_pricing_schedule_hash = '${hash}',
        seeded_by_migration = '${SEED_MIGRATION_ID}'
    WHERE singleton_key = 'GLOBAL';
  IF EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'platform_pricing_state_immutable') THEN
    EXECUTE 'ALTER TABLE platform_pricing_state ENABLE TRIGGER platform_pricing_state_immutable';
  END IF;
END
$$;
`;

// Force LF: the G-Backup runtime-migration-set hash is over exact file bytes, and .gitattributes pins
// drizzle SQL to eol=lf. Emitting CRLF (this .ts file may itself be CRLF on Windows) would break that.
writeFileSync('drizzle/0070_pricing_schedule_v5.sql', sql.replace(/\r\n/g, '\n'));
console.log('wrote 0070 seed:', { hash, entries: entries.length });
