/**
 * One-shot generator for drizzle/0062_pricing_schedule_v2.sql. Emits the seed
 * SQL from the SAME functions the tests verify against (buildSeedEntries /
 * computeSeedScheduleHash), so the migration literal cannot drift from the
 * runtime expectation. Kept in-repo for provenance; safe to re-run (it only
 * rewrites the migration file).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import {
  PRICING_SOURCE_VERSION,
  SEED_MIGRATION_ID,
  SEED_SCHEDULE_ID,
  buildSeedEntries,
  computeSeedScheduleHash,
} from '../../src/domain/pricing/pricing-foundation';

const hash = computeSeedScheduleHash();
const entries = buildSeedEntries();
const lit = (v: string | bigint | null): string => (v === null ? 'NULL' : `'${v}'`);

const rows = entries
  .map(
    (e) =>
      `  ('${SEED_SCHEDULE_ID}','${e.provider}','${e.model}',${e.inputUnitPriceMicros},${e.outputUnitPriceMicros},${e.tokenUnitSize},'${e.unitDefinition}',${e.minChargeMicros === null ? 'NULL' : e.minChargeMicros},${e.maxOutputTokens},${lit(e.validFrom)},${lit(e.validUntil)})`,
  )
  .join(',\n');

// Preserve whatever schema DDL drizzle-kit generated for this migration (the
// enum→text ALTER on pricing_schedule_entries.provider) and append the seed.
const generated = readFileSync('drizzle/0062_pricing_schedule_v2.sql', 'utf8').trim();
const schemaDdl = generated.split('-- 0062: pricing schedule v2')[0]!.trim();

const sql = `${schemaDdl}
--> statement-breakpoint
-- 0062: pricing schedule v2 — supersedes the 0053 seed after MODEL_PRICING gained the google (Gemini)
-- and deepseek models (2026-08-15). Same immutable-seed design as 0053: the v1 schedule rows are HISTORY and
-- stay untouched; a NEW schedule is inserted and the GLOBAL pointer moves to it. The ALTER above moves the
-- entries' provider column to text so this seed (and any future one) can reference providers whose enum
-- values were added in the SAME migration batch — Postgres <18 rejects that for enum columns (55P04).
-- The platform_pricing_state immutability trigger (created by rls.sql, so absent during a fresh-DB
-- bootstrap) is disabled around the pointer UPDATE — migrations ARE the platform seeding path the trigger's
-- design carves out ("only the migration/platform (superuser) role seeds these rows").
-- Generated by scripts/dev/generate-pricing-seed-0062.ts.
INSERT INTO "pricing_schedules" ("id","source_pricing_version","currency","schedule_hash","canonicalization_version","hash_algorithm","seeded_by_migration") VALUES ('${SEED_SCHEDULE_ID}','${PRICING_SOURCE_VERSION}','USD','${hash}',1,'sha256','${SEED_MIGRATION_ID}');
--> statement-breakpoint
INSERT INTO "pricing_schedule_entries" ("schedule_id","provider","model","input_unit_price_micros","output_unit_price_micros","token_unit_size","unit_definition","min_charge_micros","max_output_tokens","valid_from","valid_until") VALUES
${rows};
--> statement-breakpoint
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'platform_pricing_state_immutable') THEN
    EXECUTE 'ALTER TABLE platform_pricing_state DISABLE TRIGGER platform_pricing_state_immutable';
  END IF;
  UPDATE platform_pricing_state
    SET current_pricing_schedule_id = '${SEED_SCHEDULE_ID}',
        current_pricing_schedule_hash = '${hash}',
        seeded_by_migration = '${SEED_MIGRATION_ID}'
    WHERE singleton_key = 'GLOBAL';
  IF EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'platform_pricing_state_immutable') THEN
    EXECUTE 'ALTER TABLE platform_pricing_state ENABLE TRIGGER platform_pricing_state_immutable';
  END IF;
END
$$;
`;

writeFileSync('drizzle/0062_pricing_schedule_v2.sql', sql);
console.log('wrote 0062 seed:', { hash, entries: entries.length });
